### ISSUE TITLE
The collectd db

### ISSUE THREAD

**Issue by suntong** [testsmith-io/jmeter-influxdb-grafana-docker#2]
https://github.com/testsmith-io/jmeter-influxdb-grafana-docker/blob/357192db5b66cc7dbe73d361a68cc54f032c3840/influxdb/influx_init.iql#L2

Hi, 

What's the purpose of the `collectd` db? Thx!

**Comment by testsmith-io** [comment]
Hello,

Thanks for your interest. Sorry for the late reply! I was not able to answer earlier, due to vacation.

`collectd` is not used in this setup. However the application servers can write the server metrics to this database.

See also: [https://linux.die.net/man/1/collectd](https://linux.die.net/man/1/collectd)

Roy

**Comment by suntong** [comment]
Thanks for your reply/help.
